### PR TITLE
chore: Bump logger-conf and other libs through go mod tidy

### PR DESCRIPTION
**Pull request by ghislainbourgeois**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
Hi @ghislainbourgeois,

FYI, I understood that Gulsum was replacing the `MongoDBLibrary` with the `util/mongoapi`

**Comment by ghislainbourgeois** [comment]
@gab-arrobo good point, this was to be able to remove `path_util`, but we can maybe wait for using `util/mongoapi` instead.

**Comment by gab-arrobo** [comment]
> @gab-arrobo good point, this was to be able to remove `path_util`, but we can maybe wait for using `util/mongoapi` instead.

I am ok reviewing and merging this PR but I wanted to double check with you on how to proceed. Please let me know.

**Review by gab-arrobo — APPROVED** [review]
+1 (Tested changes with E2E AiaB deployment using `replace` directive in the `amf` and `smf` images)

**Pull request merged**
