### PR TITLE
Keep trying until it connects to Mongodb

### PR DESCRIPTION
**Pull request by vthiruveedula**

### CODE REVIEW

**Review by thakurajayL — CHANGES_REQUESTED** [review]

**Comment by thakurajayL** [comment]
@vthiruveedula  can you check why this lint error coming ?

**Comment by gab-arrobo** [comment]
@vthiruveedula @thakurajayL, is this PR still valid?

**Review by thakurajayL — APPROVED** [review]

**Comment by thakurajayL** [comment]
retest this please

**Comment by gab-arrobo** [comment]
@vthiruveedula, can you please rebase this PR (your branch)? Thanks!

**Comment by thakurajayL** [comment]
opened new request.

**Pull request closed without merging**
